# Diagnostic reproduction for the audited 0.3.0 source; run from repository root.
pkgload::load_all('.', quiet=TRUE)
cat('POSITIVE CLASS GLM\n')
d <- data.frame(x=rep(c(-2,-1,0,1,2),4), y=factor(rep(c('no','no','no','yes','yes'),4),levels=c('no','yes')))
f <- suppressWarnings(glm(y~x, d, family=binomial()))
e_yes <- explain_model(f,d,'y',positive='yes')
e_no <- explain_model(f,d,'y',positive='no')
print(cbind(p_yes=predict(e_yes,d),p_no=predict(e_no,d))[c(1,5),]); cat('max complement error:',max(abs(predict(e_no,d) - (1-predict(e_yes,d)))),'\n')
cat('FACTOR REGRESSION OUTPUT\n')
e <- explain_model(NULL, data.frame(x=1:4), 1:4,task='regression', predict_function=function(newdata) factor(rep('100',nrow(newdata)),levels=c('10','100')))
print(predict(e,data.frame(x=1:4)))
cat('UNKNOWN BINARY LABELS\n')
e <- explain_model(NULL,d,'y',predict_function=function(newdata) rep('typo',nrow(newdata)))
print(predict(e,d))
cat('FINGERPRINT CHANGED MODEL/DATA\n')
f1 <- lm(mpg~wt,mtcars); f2 <- lm(mpg~wt+hp,mtcars)
e1 <- explain_model(f1,mtcars,'mpg',label='same'); e2 <- explain_model(f2,transform(mtcars,mpg=mpg+100),'mpg',label='same')
print(c(e1$provenance$fingerprint,e2$provenance$fingerprint))
cat('CUSTOM ONE ARG PLUS ELLIPSIS\n')
print(tryCatch(explain_model(NULL,mtcars,'mpg',predict_function=function(newdata,...) rep(0,nrow(newdata))),error=conditionMessage))
cat('SERIALIZED SIZE\n')
r <- autoxplain(mtcars,'mpg',explain=FALSE)
cat('object.size:',format(object.size(r),units='auto'),'serialized:',length(serialize(r,NULL)),'\n')
cat('logical preprocessing\n')
p <- preprocess_data(data.frame(x=c(TRUE,FALSE,TRUE,NA),y=1:4),'y',missing_value_strategy='impute'); print(str(p$data))
