# Diagnostic reproduction for the audited 0.3.0 source; run from repository root.
pkgload::load_all('.', quiet=TRUE)
cat('\n1 SINGLETON STRATA\n')
d <- data.frame(x=1:20, stratum=factor(1:20), y=1:20)
e <- explain_model(list(),d,'y',task='regression',predict_function=function(newdata)newdata$x)
set.seed(4)
p <- AutoXplainR:::stratified_permutation(nrow(d),d$stratum)
print(p)
cat('rows crossing strata:',sum(p!=seq_len(nrow(d))),'; unique rows:',length(unique(p)),'\n')
pfi <- calculate_permutation_importance(e,features='x',within='stratum',n_repeats=20,seed=4)
print(as.data.frame(pfi)[,c('feature','importance','conf_low','conf_high')])
cat('\n2 ALE UNEQUAL BINS\n')
d <- data.frame(x=c(seq(0,1,length.out=51), seq(10,100,length.out=50)))
d$y <- 3*d$x
ex <- explain_model(list(),d,'y',task='regression',predict_function=function(newdata)3*newdata$x)
a <- calculate_accumulated_local_effects(ex,feature='x',n_points=4)
print(as.data.frame(a)[,c('x','accumulated_effect','n')])
cat('secant slopes:',diff(a$accumulated_effect)/diff(a$x),'expected: all 3\n')
cat('\n3 AUDIT ROW ALIGNMENT\n')
d <- data.frame(x=1:50,y=2*(1:50))
e1 <- explain_model(list(),d,'y',task='regression',label='same model ordered',predict_function=function(newdata)2*newdata$x)
e2 <- explain_model(list(),d[50:1,],'y',task='regression',label='same model reversed',predict_function=function(newdata)2*newdata$x)
a <- audit_explanations(list(e1,e2),n_repeats=20)
print(a$performance)
print(a$prediction_agreement)
print(a$findings[,c('code','message')])
cat('\n4 DEPENDENCE FEATURE SUBSET\n')
d <- data.frame(x=1:100,proxy=1:100,y=1:100)
e <- explain_model(list(),d,'y',task='regression',predict_function=function(newdata)newdata$x)
a1 <- audit_explanations(e,features=c('x','proxy'),n_repeats=20)
a2 <- audit_explanations(e,features='x',n_repeats=20)
print(a1$importance[,c('feature','max_association','evidence_grade','claim')])
print(a2$importance[,c('feature','max_association','evidence_grade','claim')])
cat('\n5 DETERMINISTIC NONMONOTONE DEPENDENCE\n')
x <- rep(seq(-1,1,length.out=101),each=2)
d <- data.frame(x=x,proxy=x^2,y=x^2)
e <- explain_model(list(),d,'y',task='regression',predict_function=function(newdata)newdata$x^2)
a <- audit_explanations(e,features=c('x','proxy'),n_repeats=20)
print(a$importance[,c('feature','max_association','evidence_grade','claim')])
cat('\n6 SUBGROUP PREPROCESSED IDENTITY\n')
train <- data.frame(x=1:30,group=rep(c('a','b','a'),10),y=1:30+rep(c(0,3,0),10))
test <- data.frame(x=31:42,group=c(rep('a',3),rep('b',3),rep('new',3),rep(NA,3)),y=31:42)
r <- autoxplain(train,'y',test_data=test,explain=FALSE)
print(table(test$group,useNA='ifany'))
print(subgroup_performance(r,by='group',min_rows=1)$performance[,c('group','rows','rmse')])
cat('\n7 THRESHOLD EDGE CASES\n')
print(AutoXplainR:::threshold_performance(rep(FALSE,10),rep(.1,10),.5,1,1))
print(AutoXplainR:::threshold_performance(c(FALSE,FALSE,TRUE,TRUE),c(.9,.8,.2,.1),.5,1,1))
cat('\n8 H2O INPUT PREPROCESSING BOUNDARY (NO LIVE ENGINE)\n')
train <- data.frame(x=c(NA,1:9,101:110),y=1:20)
test <- data.frame(x=201:202,y=21:22)
config <- list(enable_id_removal=FALSE,missing_value_strategy='impute',novel_level_strategy='mode')
a <- AutoXplainR:::prepare_h2o_outer_split(train,test,'y','regression',.2,12,TRUE,config)
train2 <- train; train2$x[11:20] <- 10001:10010
b <- AutoXplainR:::prepare_h2o_outer_split(train2,test,'y','regression',.2,12,TRUE,config)
cat('Changing only a hypothetical inner validation fold changes missing analysis-row value from',a$training$data$x[1],'to',b$training$data$x[1],'\n')
cat('\n9 AUDIT POSITIVE-CLASS SEMANTICS (COMPANION TO 3)\n')
d <- data.frame(x=seq_len(50)); d$y <- factor(ifelse(d$x>25,'yes','no'))
e1 <- explain_model(list(),d,'y',task='binary',positive='yes',label='predict yes',predict_function=function(newdata)plogis((newdata$x-25.5)/5))
e2 <- explain_model(list(),d,'y',task='binary',positive='no',label='predict no',predict_function=function(newdata)1-plogis((newdata$x-25.5)/5))
a <- audit_explanations(list(e1,e2),n_repeats=20)
print(a$performance); print(a$prediction_agreement)
cat('\n10 ALE TIED VALUES (COMPANION TO 2)\n')
d <- data.frame(x=rep(0:4,each=10)); d$y <- d$x
ex <- explain_model(list(),d,'y',task='regression',predict_function=function(newdata)newdata$x)
a <- calculate_accumulated_local_effects(ex,feature='x',n_points=20)
print(as.data.frame(a)[,c('x','accumulated_effect','n')])
cat('effect span',diff(range(a$accumulated_effect)),'grid span',diff(range(a$x)),'\n')
