test_that("individual identifiers cannot masquerade as perfect association", {
  id <- paste0("record-", seq_len(40))
  set.seed(78)
  value <- rnorm(40)
  association <- AutoXplainR:::feature_association
  expect_true(is.na(association(id, value)))
  expect_true(is.na(association(id, rep(c("A", "B"), 20))))
  checked <- AutoXplainR:::dependence_table(data.frame(id = id, value = value), .7)
  expect_true(all(is.na(checked$max_association)))
  expect_identical(checked$screen_status, rep("association_unavailable", 2))
  expect_false(any(checked$high_dependence))
  expect_identical(checked$predictors_unavailable, c(1L, 1L))
  model <- lm(value ~ 1)
  explainer <- explain_model(model, data.frame(id = id, value = value), "value")
  audit <- audit_explanations(explainer, n_repeats = 2)
  expect_identical(audit$diagnostic_status$association$status, "inapplicable")
  expect_true("association_screen_scope" %in% audit$findings$code)
})

test_that("observed-cell association matches an independent dense contingency reference", {
  set.seed(945)
  x <- rep(paste0("x", seq_len(1200)), each = 3)
  y <- sample(rep(paste0("y", seq_len(1100)), length.out = length(x)))
  counts <- table(x, y)
  expected <- outer(rowSums(counts), colSums(counts)) / sum(counts)
  statistic <- sum((counts - expected)^2 / expected)
  reference <- sqrt(statistic / (sum(counts) * (min(dim(counts)) - 1)))
  value <- AutoXplainR:::feature_association(x, y)
  expect_equal(value, reference, tolerance = 1e-13)
  expect_equal(AutoXplainR:::feature_association(y, x), reference, tolerance = 1e-13)
})
