test_that("local narratives are deterministic and limitation-first", {
  fixture <- make_regression_fixture()
  explainer <- explain_model(fixture$model, fixture$test, "y",
                             metadata = list(evaluation_role = "test"))
  audit <- audit_explanations(explainer, features = c("x1", "x2"), n_repeats = 4)
  first <- generate_natural_language_report(audit, use_remote = FALSE)
  second <- generate_natural_language_report(audit, use_remote = FALSE)
  expect_identical(first, second)
  expect_equal(attr(first, "narrative_provenance")$provider_used, "local")
  expect_false(attr(first, "narrative_provenance")$remote)
  expect_match(first, "not a certification", ignore.case = TRUE)
  expect_match(first, "not be read as causal", ignore.case = TRUE)
})

test_that("evidence prompt constrains unsupported claims", {
  context <- list(
    task_type = "regression", target_column = "y", n_models = 2,
    n_features = 3, best_model_type = "lm", best_metric = "rmse",
    best_performance = 1.2, disclosure = "aggregated"
  )
  prompt <- AutoXplainR:::create_report_prompt(context)
  expect_match(prompt, "Never imply causality")
  expect_match(prompt, "never certification")
  expect_false(grepl("GEMINI_API_KEY", prompt, fixed = TRUE))
})

test_that("local is the default even when a hosted-provider key exists", {
  withr::local_envvar(GEMINI_API_KEY = "must-not-trigger-a-request")
  result <- autoxplain(mtcars, "mpg", seed = 2)
  called <- FALSE
  report <- generate_natural_language_report(
    result,
    transport = function(request) {
      called <<- TRUE
      "unexpected"
    }
  )

  expect_false(called)
  expect_match(report, "held-out test")
  expect_match(report, "What the main metric means")
  expect_equal(attr(report, "narrative_provenance")$provider_requested, "local")
})

test_that("provider registry makes current trade-offs inspectable", {
  providers <- narrative_providers()
  expect_equal(providers$provider, c(
    "local", "gemini", "groq", "cloudflare", "ollama", "openrouter", "custom"
  ))
  expect_equal(providers$default_model[providers$provider == "gemini"],
               "gemini-3.5-flash")
  expect_equal(providers$default_model[providers$provider == "groq"],
               "openai/gpt-oss-120b")
  expect_equal(
    providers$account_environment_variable[providers$provider == "cloudflare"],
    "CLOUDFLARE_ACCOUNT_ID"
  )
  expect_true(providers$structured_output[providers$provider == "groq"])
  expect_match(
    providers$free_access[providers$provider == "cloudflare"],
    "10,000 neurons"
  )
  expect_match(
    providers$reproducibility[providers$provider == "openrouter"],
    "different free models"
  )
})

test_that("hosted and local model adapters share one sanitized prompt contract", {
  result <- autoxplain(mtcars, "mpg", seed = 6)
  result$training_data$mpg[[1L]] <- 987654321
  cases <- list(
    gemini = list(key = "gemini-secret", model = "gemini-test", url = "generateContent"),
    groq = list(key = "groq-secret", model = "groq-test", url = "groq.com"),
    cloudflare = list(
      key = "cloudflare-secret", model = "cloudflare-test",
      url = "accounts/test-account/ai/v1/chat/completions",
      account_id = "test-account"
    ),
    ollama = list(key = NULL, model = "ollama-test", url = "localhost:11434"),
    openrouter = list(key = "router-secret", model = "router-test", url = "openrouter.ai")
  )

  for (provider in names(cases)) {
    captured <- NULL
    details <- cases[[provider]]
    report <- generate_natural_language_report(
      result,
      provider = provider,
      api_key = details$key,
      model = details$model,
      account_id = details$account_id %||% NULL,
      transport = function(request) {
        captured <<- request
        paste("Generated by", provider)
      }
    )
    expect_match(captured$url, details$url, fixed = TRUE)
    expect_equal(captured$model, details$model)
    expect_match(captured$body |> unlist() |> paste(collapse = " "), "Never imply causality")
    expect_false(grepl("987654321", captured$body |> unlist() |> paste(collapse = " "),
                       fixed = TRUE))
    expect_equal(attr(report, "narrative_provenance")$provider_used, provider)
    expect_false(attr(report, "narrative_provenance")$fallback)
  }
})

test_that("custom OpenAI-compatible endpoints and provenance are supported", {
  result <- autoxplain(mtcars, "mpg", seed = 7)
  captured <- NULL
  report <- generate_natural_language_report(
    result,
    provider = "custom",
    model = "local/model",
    base_url = "http://127.0.0.1:9000/v1/chat/completions",
    transport = function(request) {
      captured <<- request
      "Custom narrative"
    }
  )

  expect_equal(captured$response_format, "openai")
  expect_equal(captured$body$model, "local/model")
  expect_equal(attr(report, "narrative_provenance")$model, "local/model")
  expect_false(attr(report, "narrative_provenance")$remote)
})

test_that("provider failures fall back transparently or can be made strict", {
  result <- autoxplain(mtcars, "mpg", seed = 9)
  withr::local_envvar(GEMINI_API_KEY = NA)
  expect_warning(
    report <- generate_natural_language_report(result, provider = "gemini"),
    "requires `api_key`"
  )
  provenance <- attr(report, "narrative_provenance")
  expect_true(provenance$fallback)
  expect_equal(provenance$provider_requested, "gemini")
  expect_equal(provenance$provider_used, "local")
  expect_match(provenance$error, "GEMINI_API_KEY")

  expect_error(
    generate_natural_language_report(
      result, provider = "groq", api_key = "key", fallback = FALSE,
      transport = function(request) stop("rate limited")
    ),
    "rate limited"
  )
  expect_error(
    generate_natural_language_report(
      result, provider = "custom", model = "model", fallback = FALSE
    ),
    "base_url"
  )
})

test_that("Cloudflare requires both scoped credentials", {
  result <- autoxplain(mtcars, "mpg", seed = 11)
  withr::local_envvar(c(
    CLOUDFLARE_API_TOKEN = NA,
    CLOUDFLARE_ACCOUNT_ID = NA
  ))

  expect_error(
    generate_natural_language_report(
      result, provider = "cloudflare", api_key = "token", fallback = FALSE
    ),
    "account_id"
  )
  expect_error(
    generate_natural_language_report(
      result, provider = "cloudflare", account_id = "account", fallback = FALSE
    ),
    "CLOUDFLARE_API_TOKEN"
  )
})
