test_that("local narratives are deterministic and limitation-first", {
  fixture <- make_regression_fixture()
  explainer <- explain_model(fixture$model, fixture$test, "y",
                             metadata = list(evaluation_role = "test"))
  audit <- audit_explanations(explainer, features = c("x1", "x2"), n_repeats = 4)
  first <- generate_natural_language_report(audit, use_remote = FALSE)
  second <- generate_natural_language_report(audit, use_remote = FALSE)
  expect_identical(first, second)
  expect_equal(attr(first, "narrative_provenance")$provider_used, "local")
  expect_false(attr(first, "narrative_provenance")$remote)
  expect_match(first, "not a certification", ignore.case = TRUE)
  expect_match(first, "not be read as causal", ignore.case = TRUE)
})

test_that("evidence prompt constrains unsupported claims", {
  context <- list(
    task_type = "regression", target_column = "y", n_models = 2,
    n_features = 3, best_model_type = "lm", best_metric = "rmse",
    best_performance = 1.2, disclosure = "aggregated"
  )
  prompt <- AutoXplainR:::create_report_prompt(context)
  expect_match(prompt, "Never imply causality")
  expect_match(prompt, "never certification")
  expect_false(grepl("GEMINI_API_KEY", prompt, fixed = TRUE))
})

test_that("local is the default even when a hosted-provider key exists", {
  withr::local_envvar(GEMINI_API_KEY = "must-not-trigger-a-request")
  result <- autoxplain(mtcars, "mpg", seed = 2)
  called <- FALSE
  report <- generate_natural_language_report(
    result,
    transport = function(request) {
      called <<- TRUE
      "unexpected"
    }
  )

  expect_false(called)
  expect_match(report, "test rows")
  expect_match(report, "What the main metric means")
  expect_equal(attr(report, "narrative_provenance")$provider_requested, "local")
})

test_that("provider registry makes current trade-offs inspectable", {
  providers <- narrative_providers()
  expect_equal(providers$provider, c(
    "local", "gemini", "groq", "cloudflare", "ollama", "openrouter", "custom"
  ))
  expect_equal(providers$default_model[providers$provider == "gemini"],
               "gemini-3.5-flash")
  expect_equal(providers$default_model[providers$provider == "groq"],
               "openai/gpt-oss-120b")
  expect_equal(
    providers$account_environment_variable[providers$provider == "cloudflare"],
    "CLOUDFLARE_ACCOUNT_ID"
  )
  expect_true(providers$structured_output[providers$provider == "groq"])
  expect_match(
    providers$free_access[providers$provider == "cloudflare"],
    "10,000 neurons"
  )
  expect_match(
    providers$reproducibility[providers$provider == "openrouter"],
    "different free models"
  )
})

test_that("hosted and local model adapters share one sanitized prompt contract", {
  result <- autoxplain(mtcars, "mpg", seed = 6)
  result$training_data$mpg[[1L]] <- 987654321
  cases <- list(
    gemini = list(key = "gemini-secret", model = "gemini-test", url = "interactions"),
    groq = list(key = "groq-secret", model = "groq-test", url = "groq.com"),
    cloudflare = list(
      key = "cloudflare-secret", model = "cloudflare-test",
      url = "accounts/test-account/ai/v1/chat/completions",
      account_id = "test-account"
    ),
    ollama = list(key = NULL, model = "ollama-test", url = "localhost:11434"),
    openrouter = list(key = "router-secret", model = "router-test", url = "openrouter.ai")
  )

  for (provider in names(cases)) {
    captured <- NULL
    details <- cases[[provider]]
    report <- generate_natural_language_report(
      result,
      provider = provider,
      api_key = details$key,
      model = details$model,
      account_id = details$account_id %||% NULL,
      structured = FALSE,
      transport = function(request) {
        captured <<- request
        paste("Generated by", provider)
      }
    )
    expect_match(captured$url, details$url, fixed = TRUE)
    expect_equal(captured$model, details$model)
    expect_match(captured$body |> unlist() |> paste(collapse = " "), "Never imply causality")
    expect_false(grepl("987654321", captured$body |> unlist() |> paste(collapse = " "),
                       fixed = TRUE))
    expect_equal(attr(report, "narrative_provenance")$provider_used, provider)
    expect_false(attr(report, "narrative_provenance")$fallback)
    if (provider == "gemini") {
      expect_false(captured$body$store)
      expect_equal(captured$body$generation_config$max_output_tokens, 4000L)
    }
  }
})

test_that("custom OpenAI-compatible endpoints and provenance are supported", {
  result <- autoxplain(mtcars, "mpg", seed = 7)
  captured <- NULL
  report <- generate_natural_language_report(
    result,
    provider = "custom",
    model = "local/model",
    base_url = "http://127.0.0.1:9000/v1/chat/completions",
    transport = function(request) {
      captured <<- request
      "Custom narrative"
    }
  )

  expect_equal(captured$response_format, "openai")
  expect_equal(captured$body$model, "local/model")
  expect_equal(attr(report, "narrative_provenance")$model, "local/model")
  expect_false(attr(report, "narrative_provenance")$remote)
})

test_that("plain HTTP narrative endpoints are restricted to loopback hosts", {
  loopback <- c(
    "http://localhost",
    "http://localhost:11434/v1/chat/completions",
    "http://127.9.8.7:9000/v1/chat/completions",
    "http://[::1]/v1/chat/completions"
  )
  for (endpoint in loopback) {
    config <- AutoXplainR:::resolve_narrative_provider(
      "custom", "local-model", endpoint, NULL
    )
    expect_false(config$remote, info = endpoint)
  }
  for (endpoint in c(
    "http://example.com/v1/chat/completions",
    "http://localhost.evil.test/v1/chat/completions",
    "http://128.0.0.1/v1/chat/completions"
  )) {
    expect_error(
      AutoXplainR:::resolve_narrative_provider(
        "custom", "remote-model", endpoint, NULL
      ),
      "must use HTTPS",
      info = endpoint
    )
  }
  secure <- AutoXplainR:::resolve_narrative_provider(
    "custom", "remote-model", "https://example.com/v1/chat/completions", NULL
  )
  expect_true(secure$remote)
})

test_that("provider failures fall back transparently or can be made strict", {
  result <- autoxplain(mtcars, "mpg", seed = 9)
  withr::local_envvar(GEMINI_API_KEY = NA)
  expect_warning(
    report <- generate_natural_language_report(result, provider = "gemini"),
    "requires `api_key`"
  )
  provenance <- attr(report, "narrative_provenance")
  expect_true(provenance$fallback)
  expect_equal(provenance$provider_requested, "gemini")
  expect_equal(provenance$provider_used, "local")
  expect_match(provenance$error, "GEMINI_API_KEY")

  expect_error(
    generate_natural_language_report(
      result, provider = "groq", api_key = "key", fallback = FALSE,
      transport = function(request) stop("rate limited")
    ),
    "rate limited"
  )
  expect_error(
    generate_natural_language_report(
      result, provider = "custom", model = "model", fallback = FALSE
    ),
    "base_url"
  )
})

test_that("Cloudflare requires both scoped credentials", {
  result <- autoxplain(mtcars, "mpg", seed = 11)
  withr::local_envvar(c(
    CLOUDFLARE_API_TOKEN = NA,
    CLOUDFLARE_ACCOUNT_ID = NA
  ))

  expect_error(
    generate_natural_language_report(
      result, provider = "cloudflare", api_key = "token", fallback = FALSE
    ),
    "account_id"
  )
  expect_error(
    generate_natural_language_report(
      result, provider = "cloudflare", account_id = "account", fallback = FALSE
    ),
    "CLOUDFLARE_API_TOKEN"
  )
})

test_that("supported providers request one validated narrative schema", {
  result <- autoxplain(mtcars, "mpg", seed = 13)
  response <- paste0(
    '{"headline":"A useful held-out result",',
    '"performance":"RMSE is the typical prediction error on held-out rows.",',
    '"patterns":["Weight was used as a predictive pattern."],',
    '"cautions":["This evaluation sample is finite."],',
    '"next_steps":["Check performance on later data."]}'
  )
  cases <- list(
    gemini = list(key = "gemini-key", model = "gemini-3.5-flash"),
    groq = list(key = "groq-key", model = "openai/gpt-oss-120b"),
    ollama = list(key = NULL, model = "gemma3:4b"),
    openrouter = list(key = "openrouter-key", model = "openrouter/free")
  )

  for (provider in names(cases)) {
    captured <- NULL
    report <- generate_natural_language_report(
      result,
      provider = provider,
      api_key = cases[[provider]]$key,
      model = cases[[provider]]$model,
      transport = function(request) {
        captured <<- request
        response
      }
    )

    expect_true(captured$structured, info = provider)
    schema <- if (provider == "gemini") {
      captured$body$response_format$schema
    } else {
      captured$body$response_format$json_schema$schema
    }
    expect_equal(schema$required, c(
      "headline", "performance", "patterns", "cautions", "next_steps"
    ), info = provider)
    expect_false(schema$additionalProperties, info = provider)
    for (field in c("patterns", "cautions", "next_steps")) {
      expect_identical(schema$properties[[field]]$minItems, 1L, info = provider)
      expect_identical(schema$properties[[field]]$maxItems, 3L, info = provider)
    }
    if (provider == "gemini") {
      expect_false(captured$body$store)
      expect_equal(captured$body$generation_config$temperature, 1)
      expect_equal(captured$body$response_format$mime_type, "application/json")
    }
    if (provider != "gemini") {
      expect_true(captured$body$response_format$json_schema$strict, info = provider)
    }
    if (provider == "openrouter") {
      expect_true(captured$body$provider$require_parameters)
    }
    expect_match(report, "# A useful held-out result", fixed = TRUE)
    expect_match(report, "Required interpretation boundaries", fixed = TRUE)
    expect_match(report, "format, not whether generated statements are true", fixed = TRUE)
    provenance <- attr(report, "narrative_provenance")
    expect_true(provenance$structured_requested, info = provider)
    expect_true(provenance$structured_used, info = provider)
  }
})

test_that("structured narrative item and total-word bounds match the schema", {
  too_many <- paste0(
    '{"headline":"Result","performance":"Held-out result.",',
    '"patterns":["one","two","three","four"],',
    '"cautions":["one"],"next_steps":["one"]}'
  )
  expect_error(
    AutoXplainR:::parse_structured_narrative(too_many),
    "1 to 3 items"
  )
  expect_error(
    AutoXplainR:::validate_narrative_word_budget(rep("word", 501L)),
    "500-word"
  )
  expect_invisible(
    AutoXplainR:::validate_narrative_word_budget(rep("word", 500L))
  )
})

test_that("structured narratives require unique root fields and JSON arrays", {
  duplicate_root <- paste0(
    '{"headline":"First","headline":"Second",',
    '"performance":"Held-out result.","patterns":["one"],',
    '"cautions":["one"],"next_steps":["one"]}'
  )
  expect_error(
    AutoXplainR:::parse_structured_narrative(duplicate_root),
    "duplicate fields: headline",
    fixed = TRUE
  )

  scalar_items <- paste0(
    '{"headline":"Result","performance":"Held-out result.",',
    '"patterns":"one","cautions":["one"],"next_steps":["one"]}'
  )
  expect_error(
    AutoXplainR:::parse_structured_narrative(scalar_items),
    "`patterns` must be an array of strings",
    fixed = TRUE
  )

  object_items <- paste0(
    '{"headline":"Result","performance":"Held-out result.",',
    '"patterns":{"first":"one"},"cautions":["one"],',
    '"next_steps":["one"]}'
  )
  expect_error(
    AutoXplainR:::parse_structured_narrative(object_items),
    "`patterns` must be an array of strings",
    fixed = TRUE
  )

  expect_error(
    AutoXplainR:::validate_narrative_items("one", "patterns"),
    "array of strings",
    fixed = TRUE
  )
  expect_error(
    AutoXplainR:::validate_narrative_items(list(first = "one"), "patterns"),
    "array of strings",
    fixed = TRUE
  )
})

test_that("unsupported schemas and invalid provider JSON are transparent", {
  result <- autoxplain(mtcars, "mpg", seed = 14)
  captured <- NULL
  report <- generate_natural_language_report(
    result,
    provider = "cloudflare",
    api_key = "cloudflare-key",
    account_id = "account",
    transport = function(request) {
      captured <<- request
      "A plain Cloudflare response."
    }
  )
  provenance <- attr(report, "narrative_provenance")

  expect_false(captured$structured)
  expect_null(captured$body$response_format)
  expect_true(provenance$structured_requested)
  expect_false(provenance$structured_used)
  expect_match(report, "Required interpretation boundaries", fixed = TRUE)

  expect_warning(
    fallback <- generate_natural_language_report(
      result,
      provider = "gemini",
      api_key = "gemini-key",
      transport = function(request) "{}"
    ),
    "missing"
  )
  expect_true(attr(fallback, "narrative_provenance")$fallback)
  expect_false(attr(fallback, "narrative_provenance")$structured_used)
  expect_error(
    generate_natural_language_report(
      result,
      provider = "gemini",
      api_key = "gemini-key",
      fallback = FALSE,
      transport = function(request) "{}"
    ),
    "missing"
  )
  expect_error(
    generate_natural_language_report(result, structured = NA),
    "structured"
  )
})

test_that("classification and missingness evidence reach the sanitized prompt", {
  set.seed(312)
  training <- data.frame(x = rnorm(120), z = rnorm(120))
  training$accepted <- factor(ifelse(
    stats::plogis(training$x - training$z) > runif(120), "yes", "no"
  ))
  evaluation <- data.frame(x = rnorm(60), z = rnorm(60))
  evaluation$accepted <- factor(ifelse(
    stats::plogis(evaluation$x - evaluation$z) > runif(60), "yes", "no"
  ), levels = levels(training$accepted))
  training$x[seq_len(6)] <- NA
  evaluation$x[seq_len(30)] <- NA
  result <- autoxplain(training, "accepted", test_data = evaluation, seed = 15)
  context <- AutoXplainR:::prepare_analysis_context(result)
  prompt <- AutoXplainR:::context_to_text(context)

  expect_match(prompt, "Probability calibration check", fixed = TRUE)
  expect_match(prompt, "Missingness check: 1 model input", fixed = TRUE)
  expect_match(prompt, "Candidate-selection boundary", fixed = TRUE)
  expect_match(prompt, "Aggregated diagnostics only", fixed = TRUE)
})

test_that("Gemini Interaction responses expose only completed model text", {
  interaction <- list(
    status = "completed",
    steps = list(
      list(type = "thought", content = list()),
      list(
        type = "model_output",
        content = list(
          list(type = "text", text = "first"),
          list(type = "image", data = "ignored"),
          list(type = "text", text = "second")
        )
      )
    )
  )

  expect_equal(
    AutoXplainR:::extract_narrative_text(
      interaction, "gemini_interactions", "gemini"
    ),
    "first\nsecond"
  )
  interaction$status <- "incomplete"
  expect_error(
    AutoXplainR:::extract_narrative_text(
      interaction, "gemini_interactions", "gemini"
    ),
    "Increase `max_tokens`"
  )
})
